theme: jekyll-theme-minimal

title: Fall 2019 Lab Notes
description: A collection of R lab notes, designed for beginner R users to help you learn how to do your own econometric analyses. Designed for Lucianna Etcheverry's Fall 2019 Class
